services:
  frontend: 
    build: ./frontend
    container_name: frontend
    ports: 
     - "3000:3000"
    stdin_open: true
    tty: true
    networks:
      - nest-network

  backend: 
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - database
    networks:
      - nest-network

  database: 
    image: "mongo"
    restart: always
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/mongodata
    networks:
      - nest-network

networks:
  nest-network:
    driver:  bridge
volumes:
  mongodata:
    driver: local  # Persist MongoDB data locally


 