services:
  frontend: 
    build: ./frontend
    container_name: frontend
    ports: 
     - "3000:3000"
    stdin_open: true
    tty: true
    # depends_on:
    #   - backend
    networks:
      - nest-network

  backend: 
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE=mongodb://mongo-db:27017/ecommerce
      - PORT=8000
      - S3_ACCESS_KEY=
      - S3_SECRET_ACCESS_KEY=
      - S3_REGION=us-east-2
      - S3_BUCKET_NAME=
      - EMAIL_HOST=
      - EMAIL_USERNAME=
      - EMAIL_PASSWORD=

    depends_on:
      - database
    networks:
      - nest-network

  database: 
    image: "mongo"
    restart: always
    container_name: mongo-db
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: test
    #   MONGO_INITDB_ROOT_PASSWORD: test@123
    ports:
      - "27017:27017"
    volumes:
      - ./mongodata:/data/db 
    networks:
      - nest-network

networks:
  nest-network:
    driver:  bridge
volumes:
  mongodata:
    driver: local  # Persist MongoDB data locally


 